version: '3.8'

services:
  agent-app:
    image: farikhan/quote_project:latest  # GitHub Action yahan push karega
    container_name: quote-agent-app
    restart: always
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      # Yahan 'db' use ho raha hai kyunke service ka naam 'db' hai
      - POSTGRES_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - AGENT_API_KEY=${AGENT_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QUOTE_API_USERNAME=${QUOTE_API_USERNAME}
      - QUOTE_API_PASSWORD=${QUOTE_API_PASSWORD}
      - GET_PRICE_API=${GET_PRICE_API}
      - QUOTE_API_URL=${QUOTE_API_URL}
      - LOG_LEVEL=INFO
    depends_on:
      db:
        condition: service_healthy # Wait karega jab tak DB ready na ho
    networks:
      - agent_network
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:16
    container_name: quote-agent-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck: # Taake app foran connect na kare jab tak DB initialize na ho
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    networks:
      - agent_network

networks:
  agent_network:
    driver: bridge